ALTER TABLE aventuras ADD COLUMN IF NOT EXISTS trace_id VARCHAR(16);
ALTER TABLE caminhos ADD COLUMN IF NOT EXISTS trace_id VARCHAR(16);
ALTER TABLE pontos_interesse ADD COLUMN IF NOT EXISTS trace_id VARCHAR(16);
